name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: 
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          docker build . --file docker/3.2/Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/labtest/itop:$(date +%s)
          docker push registry.cn-hangzhou.aliyuncs.com/labtest/itop:$(date +%s)




         
