name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and Push Docker image
      run: |
        docker login --username=${{ secrets.ALIYUNDOCKER_USERNAME }} --password=${{ secrets.ALIYUNDOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
        docker build . --file docker/3.2/Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/labtest/itop:3.2
        docker push registry.cn-hangzhou.aliyuncs.com/labtest/itop:3.2
